### ISSUE TITLE
.pdb display as cross or sphere creates artifacts

### ISSUE THREAD

**Issue by csera** [dkoes/3Dmol.js#113]
Displaying some .pdb files (straight from the RCSB database) as either spheres or crosses causes red artifacts (presumably "oxygen" atoms) to appear freely floating around the compound and not bound to anything as far as I can tell.  These artifacts persist when switching from one of these two modes to cartoon style.  However, they disappear if the style is set to stick or line.  I've attached screenshots of PDB ID: 2POR as an example.
![3dmol 2por cross - artifacts](https://cloud.githubusercontent.com/assets/12945488/8900787/01afcaee-33f8-11e5-8d9e-7d4451295c38.png)
![3dmol 2por line - no artifacts](https://cloud.githubusercontent.com/assets/12945488/8900844/720dff4a-33f8-11e5-9d88-4b0996f7599a.png)

**Comment by dkoes** [comment]
Could you provide some details of how you are switching styles?  This is the expected behavior within example.html since it only applies the cartoon style to nonhetatoms:
```viewer.setStyle({hetflag:false},{cartoon:{color: 'spectrum'}});```
If you select all the atoms and apply the style, only cartoons are shown:
```viewer.setStyle({},{cartoon:{color: 'spectrum'}});```

Single atom waters only show in sphere or cross mode, which is why line/stick mostly clears things.

**Comment by csera** [comment]
Ah, I didn't realize that sphere and cross would show water molecules when line and stick didn't.
That actually explains everything. Thanks!
