### ISSUE TITLE
Show/Hide Molecules

### ISSUE THREAD

**Issue by pablowatson** [dkoes/3Dmol.js#129]
Hi David,

Hope you are well. We met at the Boston ACS (Paul Watson, I work at Arena in San Diego) where you suggested using 3Dmol.js as a replacement for another 3D viewer. I started looking in to this and 3Dmol.js looks really nice. I added it to a webapp that lets you look at the results of superpositions and I want to hide and show molecules. I saw the the glmodel objects have a hide and show methods/functions so I presumed this would be the way to do this. However I am seeing some errors:

Uncaught TypeError: renderedMolObj.setVisible is not a function

I created a JSFiddle showing the problem (I modified one of the demo pages to include a hide/show button).

https://jsfiddle.net/drtnucoq/

Is this a bug or am I doing something stupid?

Cheers,
Paul

**Comment by dkoes** [comment]
This is fixed in 4ef5d7efd3032e687e73910dd01a63d677fcfe57

Apparently a commit 2 months ago (e1fa89b6a5704aea51dd590139b90bd8190365bd) erroneously removed the setVisible function.

I've also added a test to our test suite to make sure we catch any issues in the future.  See [here](http://3dmol.csb.pitt.edu/tests/docking.html) for a working example.
