### ISSUE TITLE
Can't use MOL2 files with embedded JS element

### ISSUE THREAD

**Issue by RitwikGupta** [dkoes/3Dmol.js#24]
There is no tag to add to the embedded js viewer to use a MOL2 file to display the molecule. This functionality exists in the online, URL controlled version.

**Comment by dkoes** [comment]
Sure there is. You can specify an externally hosted mol2 (or other file) with the href data tag:
<div style="height: 400px; width: 400px; position: relative;" class='viewer_3Dmoljs' data-href='test_structs/benzene.mol2' data-type='mol2' data-backgroundcolor='0xffffff' data-style='stick'></div>

Or, if the data is embedded in the page (e.g., in a hidden <textarea>), you can provide the id of the html element that contains the data with the data-element tag:
<div style="height: 400px; width: 400px; position: relative;" class='viewer_3Dmoljs' data-element='mol2data' data-type="mol2" data-backgroundcolor='0xffffff' data-style='stick'></div>

Now, unlike the viewer, we don't support fetching data from PubChem using a cid like we support fetching data from the PDB with pdb ids.  I don't think this is what you mean since this isn't mol2 data, but the reason we can't support it is that PubChem does not have cross-origin resource sharing (CORS) enabled.  With the hosted viewer we can use a local echo server to get around this restriction, but this doesn't work for the embedded case.

**Comment by RitwikGupta** [comment]
Wow, I didn't realize you could do that via `href`. Thank you so much!
