### ISSUE TITLE
Background Alpha Not Working

### ISSUE THREAD

**Issue by JoshuaRogan** [dkoes/3Dmol.js#52]
The alpha value doesn't change the background color with ```setBackgroundColor```. I am trying to make the viewer completely transparent but it doesn't seem to change regardless of the alpha value. The color does change but not the transparency. 

```
viewer.setBackgroundColor(0x0d0ddd, 0);
viewer.render();
```

 Is there an option to set the alpha value through a data attribute?

**Comment by dkoes** [comment]
This was indeed a problem.  This commit fixes it:
[master 7f22cf7] fix bug with transparent background colors

There were two main issues.  The first was that the alpha parameter (the second argument of setBackgroundColor) was not being properly processed and the second was that premultipliedalpha blending was being used which just doesn't result in the expected behavior.

**Comment by JoshuaRogan** [comment]
Awesome thanks for the quick fix!
