### ISSUE TITLE
transparent cartoons

### ISSUE THREAD

**Issue by dkoes** [dkoes/3Dmol.js#73]
add support for opacity property of cartoons

Note that transparent objects are not transparent to each other.

**Comment by dkoes** [comment]
I partially implemented this (6fd0d69).  Transparency is set per-chain (can't have different levels within a chain).  The opacity is taken from the last alpha carbon.  Don't support trace yet.

[Example](http://3dmol.csb.pitt.edu/viewer.html?pdb=1ycr&style=cartoon:color~blue&select=chain:B&style=cartoon:color~red,opacity~0.7)

**Comment by mattragoza** [comment]
Since transparency is a property of the material we would need to revise at what at stage material is added in the rendering process to support transparency for cartoon trace and other general shape styles (stick, sphere), where the material is currently being applied after all vertices have been added to the geometry. This would allow transparency at finer grain than per-chain control. It would also require more geometries and materials per model so this may not be optimal- we could also just apply transparency per-model for the other styles.

**Comment by dkoes** [comment]
We're not going to break up the cartoon into different geometries - that is too inefficient.  I think per-chain is a good compromise for now.  It might be more intelligent to use the average opacity of all the CA atoms.
