### ISSUE TITLE
opacity style

### ISSUE THREAD

**Issue by dkoes** [dkoes/3Dmol.js#91]
This is an extension of issue #73.

Add the ability to specify an opacity for styles.  Initially, this will **not** support per-atom transparency.  Instead we will support one opacity per model per a visual style (e.g., all sticks in the model can be transparent).  For cartoons we can support different transparency values per-chain.

Probably the best way to do this is insist that all the relevant atom styles have the same opacity.  If they don't, output a warning to the console and just do opaque.

At some point we will support more precise control of transparency, but this needs a bit of thought and a reworking of the rendering internals.

**Comment by Jenny19880324** [comment]
I don't understand why we want the feature of adding opacity for a style 
if we have a style as var style = { cartoon:{color:'spectrum',opacity:0.5}}, we can use setStyle to set the style along with the opacity property to the selected parts. ( viewer.setStyle({chain:'A'},style}));
Is it because it would be more efficient?
Can you give me an example of how this opacity for style should be called in javascript?

**Comment by mattragoza** [comment]
c79653b92c7534094bf1f6cc2f9e610f69404105 adds this feature, however it appears that transparent objects are only transparent to opaque objects. This probably also requires reworking of the rendering internals.

**Comment by dkoes** [comment]
Yes, I don't know of an efficient way to implement transparent object that are transparent to each other - you have to sort all the faces by their z depth, which I assume would be unacceptably slow for large meshes.
