### ISSUE TITLE
auto split surface meshes

### ISSUE THREAD

**Issue by dkoes** [dkoes/3Dmol.js#98]
Currently we assume that we divide the molecular volume sufficiently to avoid generating more than 2^16 vertices.  For complex surfaces this may not be true.  It also limits the chunk size for parallelism.

We should move splitMesh out of glshape and make it a general utility function.  It should then be called in generateSurfaceMesh in glviewer.

The warning message in marching cube should then be eliminated so we stop truncating vertices.  We should then test different values of maxVolume to see where the sweet spot is for performance.

**Comment by Jenny19880324** [comment]
I don't think we can use a general utility function of splitMesh to split both the mesh in glshape and the surfaceMesh.
This is because the splitMesh in glShape does not take a 3Dmol.Mesh as its argument, it take an object of this form 
{vertexArr:verts,
faceArr:faces,
nomalArr:[],
clickable:volSpec.clickable
} as its argument(i.e as mesh)

I think I can just add another version of splitMesh to split the $3Dmol.Mesh in generateSurfaceMesh or I can split the single geoGroup into several geoGroup in $3Dmol.Mesh
I don't know which method I should use( either of the two above or something else), please advise

**Comment by dkoes** [comment]
The data (vertices and faces) is the same, so just rework the function and the functions that call it so only one splitMesh utility function is needed.

**Comment by Jenny19880324** [comment]
Hi David, 
I reworked the function and made it under the namespace of 3Dmol like this
$3Dmol.splitMesh = function(mesh) {} and I still put it in glshape.js. 
Then the called it in glviewer.js but got an empty object as the return value from it. I think I didn't make the function visible in glviewer. And I have no idea how to do it.

**Comment by dkoes** [comment]
I merged the latest pull requests, but it does not actually fix the issue with test19.  If I change maxVolume back to 64000 I get the same problem.
